version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules      
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5013
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development      
    networks:
      - app_network
      
  api:
    build:
      context: ./ai.backend/ai.backend.api
      dockerfile: Dockerfile

    depends_on:
      - ai
    environment:
      - FLASK_API_URL=http://ai:8000
    volumes:
      - ./ai.backend:/app
      - /app/obj/
      - /app/bin/
    networks:
      - app_network      
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    environment:
      - FLASK_RUN_PORT=8000
    volumes:
      - ./ai:/app
    networks:
      - app_network        
    command: ["python", "app.py"]

networks:
  app_network:
    name: app_network
