version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: frontend:latest
    ports:
      - "3019:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5013
      
    networks:
      - default_digit_classifier_network
    
  api:
    build:
      context: ./ai.backend/ai.backend.api
      dockerfile: Dockerfile.prod
    image: api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FLASK_API_URL=http://ai:8000
    restart: unless-stopped
    networks:
      - default_digit_classifier_network  
  ai:
    build:
      context: ai
      dockerfile: Dockerfile  
    image: ai:latest
    networks:
      - default_digit_classifier_network
    environment:
      - FLASK_RUN_PORT=8000      



networks:
  default_digit_classifier_network:
    name: digit_classifier_network
    
