version: "3.8"

services:
  frontend:
    image: frontend:latest  # Use the pre-loaded image
    ports:
      - "3019:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5013
    networks:
      - default_digit_classifier_network

  api:
    image: api:latest  # Use the pre-loaded image
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FLASK_API_URL=http://ai:8000
    restart: unless-stopped
    networks:
      - default_digit_classifier_network

  ai:
    image: ai:latest  # Use the pre-loaded image
    environment:
      - FLASK_RUN_PORT=8000
    networks:
      - default_digit_classifier_network

networks:
  default_digit_classifier_network:
    name: digit_classifier_network
